### ISSUE TITLE
"cat: /proc/<PID>/smaps: No such file or directory" message in monitor_proc results

### ISSUE THREAD

**Issue by rraminen** [seemethere/dotfiles#2]
These usually appears  towards the end of the monitor_proc results:

0              0              0
cat: /proc/13763/smaps: No such file or directory
cat: /proc/13763/smaps: No such file or directory
0              0              0

Please suggest the a solution.

cc @jithunnair-amd

**Comment by seemethere** [comment]
This actually probable makes sense if the process isn't running anymore but still doesn't respond to `kill -0 ${pid}`.

Again like in the other issues, the script definitely isn't perfect and any help would be appreciated to improve it.

**Comment by jithunnair-amd** [comment]
@seemethere What is the significance of this line in the script?
`trap "kill -9 ${PID_TO_WATCH}" $(seq 0 15)`
It seems to result sometimes in output such as this at the end of the run:
`/data/dotfiles/bin/monitor_proc: line 1: kill: (53520) - No such process`
which again seems to be related to trying to kill an already dead process.

**Comment by seemethere** [comment]
This is so that the process is actually killed in the case where the script exits.

When developing the script I ran into a ton of issues where headless processes were running and I would have to track them down in order to actually kill the running script.

Maybe it'd be better to turn this into a function so that the script will actually check if the process is still running before it kills it.

**Comment by rraminen** [comment]
Thank you
