### ISSUE TITLE
monitor_proc on Imagenet (Distributed) gives 0 for max GPU Mem.

### ISSUE THREAD

**Issue by rraminen** [seemethere/dotfiles#3]
The output is as follows:
```
root@6c739f99adbc:/data/examples/imagenet# ./monitor_proc python main.py -a resnet50 --dist-url 'tcp://127.0.0.1:15111' --dist-backend 'nccl' --multiprocessing-distributed --world-size 1 --epochs 3 --rank 0 /data/imagenette2
Running  python main.py -a resnet50 --dist-url tcp://127.0.0.1:15111 --dist-backend nccl --multiprocessing-distributed --world-size 1 --epochs 3 --rank 0 /data/imagenette2 > "/tmp/tmp.zWH0VfTELt_monitor_proc" 2>&1 &
Watching PID: 22272
Tail log file with:
    tail -f /tmp/tmp.zWH0VfTELt_monitor_proc

Max GPU Mem.   Max RSS Mem.   Max PSS Mem.
0              182.375        90.6172
0              182.375        85.0156
0              182.375        85.0166
```

This is not the expected output. Is it? 

cc @jithunnair-amd

**Comment by seemethere** [comment]
Looks like I'm observing the same issue. Appears as though the `monitor_proc` script is not playing nicely with the python multi-processing and is watching the incorrect `PID` for the process utilizing the GPU.

**Comment by seemethere** [comment]
I see what happened, in the past the script took a variable of the `PID_TO_WATCH` instead of assuming one based on grep `ps aux`.

This is definitely something we'll have to fix but I think it'd be better overall to just rewrite `monitor_proc` in a real programming language instead of trying to hack our way through it with bash

**Comment by seemethere** [comment]
This should be resolved now.
